# Generated by Django 5.2.17 on 2026-09-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content_type', models.CharField(choices=[('news', 'Actualités'), ('arabic', 'Langue Arabe'), ('finance', 'Finance Islamique')], max_length=20, verbose_name='content type')),
                ('excerpt', models.TextField(blank=True, verbose_name='excerpt')),
                ('content', models.TextField(verbose_name='content')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='content/covers/', verbose_name='cover image')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='author')),
                ('tags', models.CharField(blank=True, max_length=255, verbose_name='tags')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié')], default='draft', max_length=20, verbose_name='status')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('ar', 'Arabic')], max_length=10, verbose_name='language')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO title')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO description')),
            ],
            options={
                'verbose_name': 'content',
                'verbose_name_plural': 'contents',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['slug'], name='content_con_slug_65e8d8_idx'), models.Index(fields=['content_type'], name='content_con_content_5aa5f4_idx'), models.Index(fields=['language'], name='content_con_languag_2046f9_idx'), models.Index(fields=['status'], name='content_con_status_665b0b_idx')],
            },
        ),
    ]
