# Generated by Django 5.2.17 on 2026-09-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('news', 'Actualités'), ('arabic', 'Langue Arabe'), ('finance', 'Finance Islamique'), ('science', 'Sciences Islamiques')], max_length=20, verbose_name='content type'),
        ),
    ]
