# Generated by Django 5.2.17 on 2026-09-05 18:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_content_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='translation_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='content',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['translation_id'], name='content_con_transla_abb1b4_idx'),
        ),
        migrations.AddConstraint(
            model_name='content',
            constraint=models.UniqueConstraint(fields=('slug', 'language'), name='unique_content_slug_language'),
        ),
    ]
