# Generated by Django 5.2.17 on 2026-09-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_content_translation_id_alter_content_slug_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='content',
            name='unique_content_slug_language',
        ),
        migrations.RemoveIndex(
            model_name='content',
            name='content_con_languag_2046f9_idx',
        ),
        migrations.RemoveIndex(
            model_name='content',
            name='content_con_transla_abb1b4_idx',
        ),
        migrations.RemoveField(
            model_name='content',
            name='language',
        ),
        migrations.RemoveField(
            model_name='content',
            name='translation_id',
        ),
        migrations.AddField(
            model_name='content',
            name='content_ar',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='content',
            name='content_en',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='content',
            name='content_fr',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='content',
            name='excerpt_ar',
            field=models.TextField(blank=True, null=True, verbose_name='excerpt'),
        ),
        migrations.AddField(
            model_name='content',
            name='excerpt_en',
            field=models.TextField(blank=True, null=True, verbose_name='excerpt'),
        ),
        migrations.AddField(
            model_name='content',
            name='excerpt_fr',
            field=models.TextField(blank=True, null=True, verbose_name='excerpt'),
        ),
        migrations.AddField(
            model_name='content',
            name='seo_description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='SEO description'),
        ),
        migrations.AddField(
            model_name='content',
            name='seo_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='SEO description'),
        ),
        migrations.AddField(
            model_name='content',
            name='seo_description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='SEO description'),
        ),
        migrations.AddField(
            model_name='content',
            name='seo_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO title'),
        ),
        migrations.AddField(
            model_name='content',
            name='seo_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO title'),
        ),
        migrations.AddField(
            model_name='content',
            name='seo_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO title'),
        ),
        migrations.AddField(
            model_name='content',
            name='slug_ar',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='content',
            name='slug_en',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='content',
            name='slug_fr',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='content',
            name='title_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='content',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='content',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='content',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['slug_fr'], name='content_con_slug_65e8d8_idx-fr'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['slug_en'], name='content_con_slug_65e8d8_idx-en'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['slug_ar'], name='content_con_slug_65e8d8_idx-ar'),
        ),
    ]
