# Generated by Django 5.2.17 on 2026-09-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_content_unique_content_slug_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='featured'),
        ),
    ]
