# Generated by Django 5.2.17 on 2026-09-14 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_content_is_featured'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='content',
            name='content_con_slug_65e8d8_idx-fr',
        ),
        migrations.RemoveField(
            model_name='content',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='content',
            name='excerpt_fr',
        ),
        migrations.RemoveField(
            model_name='content',
            name='seo_description_fr',
        ),
        migrations.RemoveField(
            model_name='content',
            name='seo_title_fr',
        ),
        migrations.RemoveField(
            model_name='content',
            name='slug_fr',
        ),
        migrations.RemoveField(
            model_name='content',
            name='title_fr',
        ),
    ]
