# Generated by Django 5.2.17 on 2026-09-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_content_content_con_slug_65e8d8_idx_fr_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='content',
            name='content_con_slug_65e8d8_idx-en',
        ),
        migrations.RemoveIndex(
            model_name='content',
            name='content_con_slug_65e8d8_idx-ar',
        ),
        migrations.RemoveField(
            model_name='content',
            name='content_ar',
        ),
        migrations.RemoveField(
            model_name='content',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='content',
            name='excerpt_ar',
        ),
        migrations.RemoveField(
            model_name='content',
            name='excerpt_en',
        ),
        migrations.RemoveField(
            model_name='content',
            name='seo_description_ar',
        ),
        migrations.RemoveField(
            model_name='content',
            name='seo_description_en',
        ),
        migrations.RemoveField(
            model_name='content',
            name='seo_title_ar',
        ),
        migrations.RemoveField(
            model_name='content',
            name='seo_title_en',
        ),
        migrations.RemoveField(
            model_name='content',
            name='slug_ar',
        ),
        migrations.RemoveField(
            model_name='content',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='content',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='content',
            name='title_en',
        ),
        migrations.AddField(
            model_name='content',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=2, verbose_name='language'),
        ),
    ]
