# Generated by Django 5.2.17 on 2026-09-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_remove_content_content_con_slug_65e8d8_idx_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('news', 'News'), ('arabic', 'Arabic Language'), ('finance', 'Islamic Finance'), ('science', 'Islamic Sciences')], max_length=20, verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='content',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20, verbose_name='status'),
        ),
    ]
