# Generated by Django 5.2.17 on 2026-09-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_translation_id_alter_course_slug_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='course',
            name='unique_course_slug_language',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='courses_cou_languag_94bd99_idx',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='courses_cou_transla_ca5348_idx',
        ),
        migrations.RemoveField(
            model_name='course',
            name='language',
        ),
        migrations.RemoveField(
            model_name='course',
            name='translation_id',
        ),
        migrations.AddField(
            model_name='course',
            name='description_ar',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='course',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='course',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='course',
            name='difficulty_ar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='difficulty'),
        ),
        migrations.AddField(
            model_name='course',
            name='difficulty_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='difficulty'),
        ),
        migrations.AddField(
            model_name='course',
            name='difficulty_fr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='difficulty'),
        ),
        migrations.AddField(
            model_name='course',
            name='estimated_duration_ar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='estimated duration'),
        ),
        migrations.AddField(
            model_name='course',
            name='estimated_duration_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='estimated duration'),
        ),
        migrations.AddField(
            model_name='course',
            name='estimated_duration_fr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='estimated duration'),
        ),
        migrations.AddField(
            model_name='course',
            name='seo_description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='SEO description'),
        ),
        migrations.AddField(
            model_name='course',
            name='seo_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='SEO description'),
        ),
        migrations.AddField(
            model_name='course',
            name='seo_description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='SEO description'),
        ),
        migrations.AddField(
            model_name='course',
            name='seo_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO title'),
        ),
        migrations.AddField(
            model_name='course',
            name='seo_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO title'),
        ),
        migrations.AddField(
            model_name='course',
            name='seo_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO title'),
        ),
        migrations.AddField(
            model_name='course',
            name='slug_ar',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='slug_en',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='slug_fr',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='title_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='course',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='course',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='module',
            name='title_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='module',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='module',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['slug_fr'], name='courses_cou_slug_2e551f_idx-fr'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['slug_en'], name='courses_cou_slug_2e551f_idx-en'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['slug_ar'], name='courses_cou_slug_2e551f_idx-ar'),
        ),
    ]
