# Generated by Django 5.2.17 on 2026-09-14 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_unique_course_slug_language_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='course',
            name='courses_cou_slug_2e551f_idx-fr',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='course',
            name='difficulty_fr',
        ),
        migrations.RemoveField(
            model_name='course',
            name='estimated_duration_fr',
        ),
        migrations.RemoveField(
            model_name='course',
            name='seo_description_fr',
        ),
        migrations.RemoveField(
            model_name='course',
            name='seo_title_fr',
        ),
        migrations.RemoveField(
            model_name='course',
            name='slug_fr',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='module',
            name='title_fr',
        ),
    ]
