# Generated by Django 5.2.17 on 2026-09-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('author', models.CharField(max_length=255, verbose_name='author')),
                ('short_description', models.TextField(blank=True, verbose_name='short description')),
                ('long_description', models.TextField(blank=True, verbose_name='long description')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='books/covers/', verbose_name='cover image')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='books/pdfs/', verbose_name='PDF file')),
                ('external_pdf_url', models.URLField(blank=True, help_text='If stored on R2 directly', verbose_name='external PDF URL')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('ar', 'Arabic')], max_length=10, verbose_name='language')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='category')),
                ('subcategory', models.CharField(blank=True, max_length=100, verbose_name='subcategory')),
                ('tags', models.CharField(blank=True, max_length=255, verbose_name='tags')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='publication date')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié')], default='draft', max_length=20, verbose_name='status')),
                ('featured', models.BooleanField(default=False, verbose_name='featured')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO title')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO description')),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'books',
                'ordering': ['order', '-publication_date'],
                'indexes': [models.Index(fields=['slug'], name='books_book_slug_ca552e_idx'), models.Index(fields=['language'], name='books_book_languag_ea595e_idx'), models.Index(fields=['status'], name='books_book_status_ea5e47_idx')],
            },
        ),
    ]
