# Generated by Django 5.2.17 on 2026-09-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_translation_id_alter_book_slug_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='book',
            name='unique_book_slug_language',
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='books_book_languag_ea595e_idx',
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='books_book_transla_ab94d9_idx',
        ),
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
        migrations.RemoveField(
            model_name='book',
            name='translation_id',
        ),
        migrations.AddField(
            model_name='book',
            name='long_description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='long description'),
        ),
        migrations.AddField(
            model_name='book',
            name='long_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='long description'),
        ),
        migrations.AddField(
            model_name='book',
            name='long_description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='long description'),
        ),
        migrations.AddField(
            model_name='book',
            name='seo_description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='SEO description'),
        ),
        migrations.AddField(
            model_name='book',
            name='seo_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='SEO description'),
        ),
        migrations.AddField(
            model_name='book',
            name='seo_description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='SEO description'),
        ),
        migrations.AddField(
            model_name='book',
            name='seo_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO title'),
        ),
        migrations.AddField(
            model_name='book',
            name='seo_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO title'),
        ),
        migrations.AddField(
            model_name='book',
            name='seo_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO title'),
        ),
        migrations.AddField(
            model_name='book',
            name='short_description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='short description'),
        ),
        migrations.AddField(
            model_name='book',
            name='short_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='short description'),
        ),
        migrations.AddField(
            model_name='book',
            name='short_description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='short description'),
        ),
        migrations.AddField(
            model_name='book',
            name='slug_ar',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='slug_en',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='slug_fr',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='book',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='book',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['slug_fr'], name='books_book_slug_ca552e_idx-fr'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['slug_en'], name='books_book_slug_ca552e_idx-en'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['slug_ar'], name='books_book_slug_ca552e_idx-ar'),
        ),
    ]
