# Generated by Django 5.2.17 on 2026-09-14 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_unique_book_slug_language_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='book',
            name='books_book_slug_ca552e_idx-fr',
        ),
        migrations.RemoveField(
            model_name='book',
            name='long_description_fr',
        ),
        migrations.RemoveField(
            model_name='book',
            name='seo_description_fr',
        ),
        migrations.RemoveField(
            model_name='book',
            name='seo_title_fr',
        ),
        migrations.RemoveField(
            model_name='book',
            name='short_description_fr',
        ),
        migrations.RemoveField(
            model_name='book',
            name='slug_fr',
        ),
        migrations.RemoveField(
            model_name='book',
            name='title_fr',
        ),
    ]
