# Generated by Django 5.2.17 on 2026-09-14 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_language'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='book',
            name='books_book_slug_ca552e_idx-en',
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='books_book_slug_ca552e_idx-ar',
        ),
        migrations.RemoveField(
            model_name='book',
            name='long_description_ar',
        ),
        migrations.RemoveField(
            model_name='book',
            name='long_description_en',
        ),
        migrations.RemoveField(
            model_name='book',
            name='seo_description_ar',
        ),
        migrations.RemoveField(
            model_name='book',
            name='seo_description_en',
        ),
        migrations.RemoveField(
            model_name='book',
            name='seo_title_ar',
        ),
        migrations.RemoveField(
            model_name='book',
            name='seo_title_en',
        ),
        migrations.RemoveField(
            model_name='book',
            name='short_description_ar',
        ),
        migrations.RemoveField(
            model_name='book',
            name='short_description_en',
        ),
        migrations.RemoveField(
            model_name='book',
            name='slug_ar',
        ),
        migrations.RemoveField(
            model_name='book',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='book',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='book',
            name='title_en',
        ),
    ]
